---

- name: package | fish
  package: name="{{ fish_name }}" state="{{ install_state }}"
  tags:
    - bootstrap
    - install

- block:
    - name: setup | determine shell executable location
      command: which fish
      register: fish

    - name: configure | change default shell
      user: name="{{ user_name }}" shell="{{ fish.stdout }}"
      become_user: "{{ user_name }}"

    # - name: setup | create config directory
    #   file: path="{{ fish_config_file | dirname }}" state=directory follow=yes

    # - name: configure | fish config file
    #   template:
    #     src: config.j2
    #     dest: "{{ fish_config_file }}"
    #     owner: "{{ user_name }}"
    #     force: yes
    #     backup: yes
  tags:
    - bootstrap
    - configure
