---

- name: install
  package: name=fish state=present
  tags:
    - bootstrap
    - install

- block:
    - name: determine shell executable location
      command: which fish
      register: fish

    - name: configure | change default shell
      user: name="{{ user_name }}" shell="{{ fish.stdout }}"
      become: yes

    - name: configure | fish config file
      template:
        src: config.j2
        dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
        owner: "{{ user_name }}"
        force: yes
        backup: yes
  tags:
    - bootstrap
    - configure
